### ISSUE TITLE
OpenSCAP Error: Document is empty

### ISSUE THREAD

**Issue by trevor-viljoen** [jhrozek/ocp4-openscap-content#4]
I'm unable to get the compliancesuite CR to complete. `oc get compliancesuites test-compliancesuite -o yaml` shows: 

```
scanStatuses:
- errormsg: |
    OpenSCAP Error: Document is empty [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:305]
    Is a directoryEntity: line 1: parser error: Document is empty
    ^
    Unable to parse XML at: '/content' [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:307]
  name: workers-scan
  phase: DONE
  result: ERROR
- errormsg: |
    OpenSCAP Error: Document is empty [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:305]
    Is a directoryEntity: line 1: parser error: Document is empty
    ^
    Unable to parse XML at: '/content' [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:307]
  name: masters-scan
  phase: DONE
  result: ERROR
```

The `contentImage` is `quay.io/jhrozek/ocp4-openscap-content:latest`.
The `profile` is `xccdf_org.ssgproject.content_profile_coreos-ncp`.

The only change to the CR from the openshift/compliance-operator repo was to change `autoApplyRemediations` to false.

**Comment by redhatrises** [comment]
@trevor-viljoen please open this at https://github.com/openshift/compliance-operator/issues

**Comment by jhrozek** [comment]
I'm sorry you're having issues with the content and that it took me so long to answer. I would also suggest to file issues for the compliance operator. I'll close this issue and reply to the one you just opened.
